import type { AboutPageData } from "@/types/content";
import { homepageData } from "./homepage";

export const aboutData: AboutPageData = {
  hero: {
    eyebrow: "01 — About Strucxal",
    headlineParts: [
      { type: "text", value: "A small studio." },
      { type: "br" },
      { type: "text", value: "Working " },
      { type: "accent", value: "deeply" },
      { type: "br" },
      { type: "text", value: "with " },
      { type: "soft", value: "a few brands a year." },
    ],
    metaLabel: "★ Studio at a glance",
    metaPills: [
      "Founded 2021",
      "5 people",
      "12 client countries",
      "40+ projects shipped",
      "HQ Nha Trang, Vietnam",
    ],
  },

  story: {
    eyebrow: "02 — Origin",
    heading: "How we got here.",
    body: "The studio didn't start from a business plan — it started from a question: \"Why does the web still feel slow and ugly when the technology is more than good enough?\"",
    events: [
      {
        year: "2021",
        title: "Started with a laptop and a café table",
        body: "Hung Khai began freelancing on Upwork, specialising in WordPress and WooCommerce. The first goal was simple: pay rent and go deeper on the web. The first client was a small florist in Canada.",
        tags: ["WordPress", "WooCommerce", "Freelance"],
      },
      {
        year: "2022",
        title: "Top Rated Plus on Upwork",
        body: "After 18 months and 30+ projects, hit Top Rated Plus with 100% Job Success. Started taking on harder work — custom plugins, payments, multi-vendor marketplaces.",
        tags: ["Top Rated Plus", "100% JS", "30+ projects"],
      },
      {
        year: "2023",
        title: "Switched stack to React and Next.js",
        body: "Hit the ceiling of what WordPress could do for modern products. Self-taught into Next.js, TypeScript, Tailwind. First project on the new stack was a SaaS dashboard for a Singapore startup.",
        tags: ["Next.js", "TypeScript", "SaaS"],
      },
      {
        year: "2024",
        yearCurrent: true,
        milestone: true,
        title: "Strucxal Studio officially launched",
        body: "Stepped out of the solo-freelance model. Brought in Thang (Lead Engineer) and Linh (UX Strategist). Registered the studio in Vietnam. Started accepting larger team-based engagements.",
        tags: ["★ Studio launch", "Team of 3", "First $50k project"],
      },
      {
        year: "2025",
        yearCurrent: true,
        milestone: true,
        title: "Breakthrough with Luma and Quartz case studies",
        body: "Two pivotal projects sharpened the positioning. Luma Atelier lifted mobile conversion by 100%. Quartz Analytics cut sales cycle by 24%. Inquiries started coming directly, not through Upwork.",
        tags: ["★ Featured cases", "Team of 5", "Direct clients"],
      },
      {
        year: "2026",
        title: "Today — and the near future",
        body: "5 people, 12 client countries, 40+ projects shipped. Building Strucxal Management — an internal product to run studio workflow. 2027 plan: launch a mentorship program for young designers and developers in Vietnam.",
        tags: ["Studio of 5", "40+ projects", "Internal product WIP"],
      },
    ],
  },

  team: {
    eyebrow: "03 — The team",
    headingTop: "Five people. No more.",
    headingBottom: "Senior team only.",
    lead: "Every member has at least eight years of experience. No junior layer, no account managers. You work directly with the people designing and coding your project.",
    members: [
      {
        name: "Hung Khai",
        role: "Founder · Design & Strategy",
        bio: "Twelve years in design and web development. Started in WordPress, switched to React/Next.js in 2023. Computer Science degree. Obsessed with type and print. Based in Nha Trang, Vietnam. Has worked with clients from 12 countries, mostly in e-commerce and SaaS.",
        portrait: "p1",
        roleTag: "★ Founder",
        skills: ["Strategy", "Design system", "Typography", "Next.js", "WordPress", "Figma"],
        socials: [
          { label: "in", href: "#", title: "LinkedIn" },
          { label: "𝕏", href: "#", title: "Twitter" },
          { label: "D", href: "#", title: "Dribbble" },
          { label: "@", href: "mailto:hello@strucxal.studio", title: "Email" },
        ],
        founder: true,
      },
      {
        name: "Thang Tran",
        role: "Lead Engineer",
        bio: "Ten years full-stack. Specialises in React, TypeScript, and database design. Mentors the team on architecture and performance work.",
        portrait: "p2",
        roleTag: "Engineering",
        skills: ["TypeScript", "React", "Postgres", "DevOps"],
      },
      {
        name: "Linh Nguyen",
        role: "UX Strategist",
        bio: "Nine years in UX research and product strategy. Background in psychology + business. Leads the discovery workshop for every new engagement.",
        portrait: "p3",
        roleTag: "Strategy",
        skills: ["UX Research", "Strategy", "Workshop", "Analytics"],
      },
      {
        name: "Minh Pham",
        role: "Frontend Engineer",
        bio: "Eight years focused on frontend animation and microinteraction. Strong in GSAP, Framer Motion, and Three.js for 3D web.",
        portrait: "p4",
        roleTag: "Frontend",
        skills: ["GSAP", "Three.js", "Framer Motion", "WebGL"],
      },
      {
        name: "Ha Vu",
        role: "Product Designer",
        bio: "Eight years in UI design and brand identity. Previously at a Singapore design agency before joining Strucxal. Strong in typography and editorial layout.",
        portrait: "p5",
        roleTag: "Design",
        skills: ["UI Design", "Brand", "Typography", "Figma"],
      },
    ],
  },

  values: {
    eyebrow: "04 — Core values",
    headingTop: "Six principles.",
    headingBottom: "They shape every call we make.",
    lead: "Not slogans on a wall — this is how we turn down projects, hire people, and measure success.",
    items: [
      {
        number: "01",
        title: "Quality over speed.",
        body: "We'll happily push a timeline two weeks to hit the standard the work deserves. We never ship something we think is \"close enough\". A late launch is recoverable. A bad launch isn't.",
        tone: "accent",
      },
      {
        number: "02",
        title: "Less but better.",
        body: "Eight to twelve engagements a year, not fifty. Every project we take gets 100% of our attention. This is why we turn down more than 60% of inquiries.",
      },
      {
        number: "03",
        title: "Direct, always.",
        body: "Clients work directly with the people designing and coding their project. No account manager, no middle layer. Communication is fast, honest, never garbled.",
        tone: "dark",
      },
      {
        number: "04",
        title: "Show, don't tell.",
        body: "We measure success by real client numbers — conversion, revenue, retention — not awards or likes. Every case study comes with specific outcomes.",
      },
      {
        number: "05",
        title: "Honest disagreement.",
        body: "If we think your idea isn't good, we say so. If there's a cheaper path for you (even if it means not hiring us), we recommend it. Respect beats flattery.",
        tone: "dark",
      },
      {
        number: "06",
        title: "Async by default.",
        body: "Meetings only when they genuinely move the work. Default is Loom + Slack threads. Everyone gets deep-work time. This is how we keep the quality high.",
        tone: "accent",
      },
    ],
  },

  stats: {
    eyebrow: "05 — By the numbers",
    headingTop: "The studio in 60 seconds.",
    headingBottom: "By real numbers.",
    items: [
      {
        label: "★ Total impact as of 2026",
        num: "$24",
        unit: "M",
        heading: "Estimated revenue our products have generated for clients",
        span: "feature",
      },
      { label: "Projects", num: "40", unit: "+", heading: "Shipped live", span: "regular" },
      { label: "Countries", num: "12", heading: "Clients served", span: "regular" },
      {
        label: "Performance",
        num: "95",
        unit: "/100",
        heading: "Average Lighthouse score across all projects",
        body: "Measured directly through Google PageSpeed Insights — not lab scores.",
        span: "wide",
      },
      {
        label: "Retention",
        num: "68",
        unit: "%",
        heading: "Clients who return within 12 months",
        body: "Or refer new clients to us — repeat business is the metric that matters most.",
        span: "wide",
      },
      { label: "Years in business", num: "5", heading: "Since 2021", span: "regular" },
      { label: "Team size", num: "5", heading: "Senior only", span: "regular" },
      { label: "Lighthouse", num: "98", unit: "%", heading: "Projects hitting 95+", span: "regular" },
      { label: "Inquiries", num: "60", unit: "%", heading: "Turned down intentionally", span: "regular" },
    ],
  },

  careers: {
    eyebrow: "06 — Careers",
    headingTop: "Join the team.",
    headingBottom: "When the right person meets the right moment.",
    ctaCard: {
      label: "★ Open application",
      body: "Don't see a role that fits? Send a portfolio anyway. We open new positions every 6–9 months and always review strong work.",
      ctaLabel: "Send open application →",
      ctaHref: "/contact",
    },
    roles: [
      {
        id: "c1",
        title: "Senior Frontend Engineer",
        meta: "★ Open · Full-time",
        location: "Remote / Vietnam",
        stack: "Next.js · TypeScript",
        status: "open",
        statusLabel: "Hiring",
      },
      {
        id: "c2",
        title: "Product Designer (Mid-Senior)",
        meta: "★ Open · Full-time",
        location: "Nha Trang / Remote",
        stack: "Figma · Framer · UX",
        status: "open",
        statusLabel: "Hiring",
      },
      {
        id: "c3",
        title: "Design Intern — Summer 2026",
        meta: "Internship · 3 months",
        location: "Nha Trang (onsite)",
        stack: "Figma · Web design",
        status: "open",
        statusLabel: "Hiring",
      },
      {
        id: "c4",
        title: "UX Researcher",
        meta: "Closed · Filled",
        location: "Remote",
        stack: "Research · Strategy",
        status: "closed",
        statusLabel: "Closed",
      },
      {
        id: "c5",
        title: "Backend Engineer",
        meta: "Closed · Filled",
        location: "Remote / Vietnam",
        stack: "Node · Postgres · Supabase",
        status: "closed",
        statusLabel: "Closed",
      },
    ],
  },

  finalCta: homepageData.finalCta,
};
