import type { WorkPageData } from "@/types/content";
import { homepageData } from "./homepage";

export const workPageData: WorkPageData = {
  hero: {
    eyebrow: "01 — Portfolio",
    headingTop: "40 projects.",
    headingBottom: "12 industries.",
    stats: [
      { num: "40", unit: "+", label: "Projects shipped" },
      { num: "12", label: "Client countries" },
      { num: "98", unit: "%", label: "Average Lighthouse" },
      { num: "$24M", label: "Estimated revenue impact" },
    ],
  },
  filterChips: [
    { label: "All", count: 40 },
    { label: "E-commerce", count: 12 },
    { label: "SaaS", count: 9 },
    { label: "Marketing site", count: 8 },
    { label: "B2B platform", count: 6 },
    { label: "Marketplace", count: 3 },
    { label: "FinTech", count: 2 },
  ],
  masonry: [
    {
      id: "p1",
      size: "wide",
      gradient: "g1",
      tag: "★ Featured",
      year: "2026 · E-COMMERCE · 6 months",
      category: "E-commerce",
      title: "Luma Atelier — 100% lift in mobile conversion",
      href: "/work/p1",
      featured: true,
    },
    {
      id: "p2",
      size: "tall",
      gradient: "g2",
      tag: "SaaS",
      year: "2025 · DASHBOARD",
      category: "SaaS",
      title: "Quartz Analytics",
      href: "/work/p2",
    },
    {
      id: "p3",
      size: "square",
      gradient: "g3",
      tag: "B2B",
      year: "2025 · INFRA",
      category: "B2B",
      title: "Nordic Cloud",
      href: "/work/p3",
    },
    {
      id: "p4",
      size: "square",
      gradient: "g4",
      tag: "Marketplace",
      year: "2025 · MARKETPLACE",
      category: "Marketplace",
      title: "Petal Art",
      href: "/work/p4",
    },
    {
      id: "p5",
      size: "regular",
      gradient: "g5",
      tag: "Studio",
      year: "2024 · PORTFOLIO",
      category: "Studio",
      title: "Atlas Architects",
      href: "/work/p5",
    },
    {
      id: "p6",
      size: "regular",
      gradient: "g4",
      tag: "FinTech",
      year: "2025 · APP",
      category: "FinTech",
      title: "Coil Wallet",
      href: "/work/p6",
    },
    {
      id: "p7",
      size: "regular",
      gradient: "g1",
      tag: "E-com",
      year: "2024 · RETAIL",
      category: "E-commerce",
      title: "Ember Goods",
      href: "/work/p7",
    },
    {
      id: "p8",
      size: "full",
      gradient: "g5",
      tag: "★ Case study",
      year: "2025 · SAAS",
      category: "SaaS",
      title: "Glyphic — 24% faster sales cycle",
      href: "/work/p8",
    },
  ],
  finalCta: homepageData.finalCta,
};
